/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#506170",
        "primary": "#37628a",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed": "#dfccfd",
        "outline-variant": "#acb3b7",
        "on-background": "#2c3437",
        "tertiary-fixed-dim": "#d1beef",
        "on-tertiary-fixed-variant": "#5a4b74",
        "on-primary-fixed-variant": "#225077",
        "on-primary-fixed": "#003354",
        "surface-tint": "#37628a",
        "surface-dim": "#d4dbdf",
        "on-surface-variant": "#596064",
        "surface-container-low": "#f0f4f7",
        "tertiary": "#675882",
        "on-primary-container": "#16476d",
        "error-dim": "#67040d",
        "error-container": "#fa746f",
        "outline": "#747c80",
        "secondary-fixed-dim": "#c5d6e8",
        "tertiary-dim": "#5a4c75",
        "background": "#f7f9fb",
        "primary-dim": "#29567d",
        "on-error-container": "#6e0a12",
        "secondary-dim": "#445564",
        "inverse-primary": "#a6d0fe",
        "inverse-on-surface": "#9a9d9f",
        "surface-container": "#eaeff2",
        "tertiary-container": "#dfccfd",
        "on-tertiary": "#fef7ff",
        "surface-variant": "#dce4e8",
        "error": "#a83836",
        "on-tertiary-container": "#50426a",
        "on-secondary-fixed-variant": "#4d5d6c",
        "primary-fixed-dim": "#98c2ef",
        "surface-container-high": "#e3e9ed",
        "primary-container": "#a6d0fe",
        "on-primary": "#f7f9ff",
        "inverse-surface": "#0b0f10",
        "on-secondary-container": "#435462",
        "surface": "#f7f9fb",
        "on-tertiary-fixed": "#3d2f56",
        "secondary-container": "#d3e5f7",
        "on-error": "#fff7f6",
        "secondary-fixed": "#d3e5f7",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#2c3437",
        "primary-fixed": "#a6d0fe",
        "on-secondary": "#f6f9ff",
        "surface-container-highest": "#dce4e8",
        "on-secondary-fixed": "#31414f"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}